# fly.toml app configuration file generated for signlingo-api on 2025-06-15T17:59:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'signlingo-api'
primary_region = 'bog'

[build]
  dockerfile = 'Presentation/Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Development'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
