<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Advertisement\" />
      <Folder Include="ExercisesManager\Model\ValueObjects\" />
      <Folder Include="Notification\" />
      <Folder Include="Ranking\Model\Agreggates\" />
      <Folder Include="Ranking\Model\Queries\" />
      <Folder Include="Ranking\Model\ValueObjects\" />
      <Folder Include="Ranking\Services\" />
      <Folder Include="Security\Model\Entities\" />
      <Folder Include="Shared\Model\" />
      <Folder Include="Transaction\" />
      <Folder Include="UserStats\Model\Entities\" />
      <Folder Include="UserStats\Model\ValueObjects\" />
    </ItemGroup>

</Project>
