<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Advertisement\" />
      <Folder Include="Notification\" />
      <Folder Include="Ranking\" />
      <Folder Include="Security\Model\Entities\" />
      <Folder Include="Transaction\" />
      <Folder Include="UserStats\Model\Entities\" />
    </ItemGroup>

</Project>
