<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Advertisement\" />
        <Folder Include="Notification\" />
        <Folder Include="Ranking\" />
        <Folder Include="Transaction\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CloudinaryDotNet" Version="1.27.6" />
        <PackageReference Include="Cronos" Version="0.11.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.5" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
        <HintPath>..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.14\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
